version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB}        
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-app:
    build:
      context: ./app
    environment:
      DATABASE_URL: ${DATABASE_URL}        
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}# leído desde .env
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data: